{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.sedis",
    "module": "api",
    "version": "1.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.1.7.jar",
          "url": "api-1.1.7.jar",
          "size": 17529,
          "sha512": "4777b5c07fa4b6c41f28ec1cb01a587cf69e122811d4c7924c1fbab79d96850e19ce998f20aaa15e53a8236c4c18605832cc30cc31ce1da2502cd9aed191874d",
          "sha256": "81efea7ae6796a0e4ef1eb1959e6d4c582145969803ad9f6ba2511279988203b",
          "sha1": "081ec58a2ca9f884a1ad3b6cf0c9301404a275a8",
          "md5": "c737bc48b3cffc98f3a8278c569cd310"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.7.jar",
          "url": "api-1.1.7.jar",
          "size": 17529,
          "sha512": "4777b5c07fa4b6c41f28ec1cb01a587cf69e122811d4c7924c1fbab79d96850e19ce998f20aaa15e53a8236c4c18605832cc30cc31ce1da2502cd9aed191874d",
          "sha256": "81efea7ae6796a0e4ef1eb1959e6d4c582145969803ad9f6ba2511279988203b",
          "sha1": "081ec58a2ca9f884a1ad3b6cf0c9301404a275a8",
          "md5": "c737bc48b3cffc98f3a8278c569cd310"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.7-sources.jar",
          "url": "api-1.1.7-sources.jar",
          "size": 16017,
          "sha512": "3b573630da172136fa2850885d47ab58b83ac3878c35b3eea7ac35ab6c83aaffd114ed97081ad727e718913ab8923199b0ef12b8cfbd4fda19bfb46732e794ef",
          "sha256": "5a5866d7bc18bf71c9731e734e3b5b33e7bb469419008f51a8283bedfeb63891",
          "sha1": "8244957969e739092208b31b84bf765dd1c280b2",
          "md5": "719b680dd2a63f32d2b98f80e1fbb07a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.7-javadoc.jar",
          "url": "api-1.1.7-javadoc.jar",
          "size": 124287,
          "sha512": "74ec14ec1963b3f75ac5d99bcc3292a8fbd628540ad44f64b1c5f632e68fb1a24cfbcc0c5cf92c1faef1bdc5746ed298ce4af9a64c4b625a6ec78df46c859381",
          "sha256": "8704211607c222c3e1d59fb3c4528b64902c3385f76dae7f5fa04164e89ea6d7",
          "sha1": "dcc8ada06cf6078c489c63cafb145bcb96f8cf6b",
          "md5": "04630a84cb876e4d1faa849f189b7f14"
        }
      ]
    }
  ]
}
