{
  "formatVersion": "1.1",
  "component": {
    "group": "org.leycm.frames",
    "module": "the-frame",
    "version": "1.3.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "the-frame-1.3.11.jar",
          "url": "the-frame-1.3.11.jar",
          "size": 44352,
          "sha512": "2c21c562113b0fd25ce2a238fd03f90d32064d44ab8e22111bd317205ac0fd929567ba10a1f762c657aa58868c112bd62786e5a96eb0b80b63366e3e7e3f415c",
          "sha256": "23c647bf729753af69822bad2d6e9e3ca27188dd0886fb93cf194ce9f3d10b79",
          "sha1": "b48ef7a3a04c75cc7d89d563ac71a40ef41336e5",
          "md5": "10c071b85775f6cebddd26dc36ba5257"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "the-frame-1.3.11.jar",
          "url": "the-frame-1.3.11.jar",
          "size": 44352,
          "sha512": "2c21c562113b0fd25ce2a238fd03f90d32064d44ab8e22111bd317205ac0fd929567ba10a1f762c657aa58868c112bd62786e5a96eb0b80b63366e3e7e3f415c",
          "sha256": "23c647bf729753af69822bad2d6e9e3ca27188dd0886fb93cf194ce9f3d10b79",
          "sha1": "b48ef7a3a04c75cc7d89d563ac71a40ef41336e5",
          "md5": "10c071b85775f6cebddd26dc36ba5257"
        }
      ]
    }
  ]
}
