{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.axle",
    "module": "common",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.0.1.jar",
          "url": "common-1.0.1.jar",
          "size": 261,
          "sha512": "ebf7df6b3415001d9af5e09de83d3f627e1aff880295ec537cf1b55098ce46defe978662bcbd36df6a5b33106f043dcb6380e2454b45f6bf65e927296974772c",
          "sha256": "469c9cccf97a12228125d94368156a1fc1e3ad3a705d4b76b00e7dceecd87428",
          "sha1": "ef6742eedbffd8d5c3e0200ed5004b7f0062bbd2",
          "md5": "15c50b7ec081562c5e9744d4bbefdd77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.0.1.jar",
          "url": "common-1.0.1.jar",
          "size": 261,
          "sha512": "ebf7df6b3415001d9af5e09de83d3f627e1aff880295ec537cf1b55098ce46defe978662bcbd36df6a5b33106f043dcb6380e2454b45f6bf65e927296974772c",
          "sha256": "469c9cccf97a12228125d94368156a1fc1e3ad3a705d4b76b00e7dceecd87428",
          "sha1": "ef6742eedbffd8d5c3e0200ed5004b7f0062bbd2",
          "md5": "15c50b7ec081562c5e9744d4bbefdd77"
        }
      ]
    }
  ]
}
