{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.vault",
    "module": "common",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.0.3.jar",
          "url": "common-1.0.3.jar",
          "size": 1536121,
          "sha512": "415ecf8b77516f765e7b17203fb2d28af8f8bec66c34a20f94d6ce4ef599bd931647ca3da4931fb846522f519d86a1cf5812637137cb6290e72e6918d685ccee",
          "sha256": "6e643637b9af43c94899eef9c1fd57ee42d0bdd51921303bf043668c951b9697",
          "sha1": "3702672a5e841dd6e66e38e53c253a706b0570b7",
          "md5": "00343349b19a58aab5fca6f033f432d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.leycm.vault",
          "module": "api",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-core",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "configurate-yaml",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "de.leycm.neck",
          "module": "api",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.3.jar",
          "url": "common-1.0.3.jar",
          "size": 1536121,
          "sha512": "415ecf8b77516f765e7b17203fb2d28af8f8bec66c34a20f94d6ce4ef599bd931647ca3da4931fb846522f519d86a1cf5812637137cb6290e72e6918d685ccee",
          "sha256": "6e643637b9af43c94899eef9c1fd57ee42d0bdd51921303bf043668c951b9697",
          "sha1": "3702672a5e841dd6e66e38e53c253a706b0570b7",
          "md5": "00343349b19a58aab5fca6f033f432d2"
        }
      ]
    }
  ]
}
