{
  "formatVersion": "1.1",
  "component": {
    "group": "org.leycm",
    "module": "neck",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "neck-1.0.4.jar",
          "url": "neck-1.0.4.jar",
          "size": 31204,
          "sha512": "0ae7b706a2fa5273158798502bb3d50e666527a8124f1758dae15134f6c921ae2d157d5d587cab81be817abe6e2097ef5a3afb05915ae824bb514ba14cad1b2c",
          "sha256": "b9e71947e1207f8c2a9b3e62803426693a680c38b256e70a22be3c5424085c0a",
          "sha1": "6e0a85392e6ba7d9755c80eb40d0e4ea04dfecc9",
          "md5": "63256cc3dccbf70e4904d0388bd84ff0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "neck-1.0.4.jar",
          "url": "neck-1.0.4.jar",
          "size": 31204,
          "sha512": "0ae7b706a2fa5273158798502bb3d50e666527a8124f1758dae15134f6c921ae2d157d5d587cab81be817abe6e2097ef5a3afb05915ae824bb514ba14cad1b2c",
          "sha256": "b9e71947e1207f8c2a9b3e62803426693a680c38b256e70a22be3c5424085c0a",
          "sha1": "6e0a85392e6ba7d9755c80eb40d0e4ea04dfecc9",
          "md5": "63256cc3dccbf70e4904d0388bd84ff0"
        }
      ]
    }
  ]
}
