{
  "formatVersion": "1.1",
  "component": {
    "group": "org.leycm",
    "module": "neck",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "neck-1.0.5.jar",
          "url": "neck-1.0.5.jar",
          "size": 37526,
          "sha512": "3907fb5e4a6740e8290020341b3771bd228369de6fb2d2258418a8560a4c1b74e48047f2325092e4aade2f95821b8d6c8b1dd0daf28a26bdadf9c8a8567b70a5",
          "sha256": "c6fe3fb2324baad85dec7541bae49cecc846cf8bbbb97bd805b4883c51cab9bd",
          "sha1": "730314834f33a558890eb125cd9ab62fe699081e",
          "md5": "40da6055ca87cb7231130f0f4a68b984"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.1"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "24.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "neck-1.0.5.jar",
          "url": "neck-1.0.5.jar",
          "size": 37526,
          "sha512": "3907fb5e4a6740e8290020341b3771bd228369de6fb2d2258418a8560a4c1b74e48047f2325092e4aade2f95821b8d6c8b1dd0daf28a26bdadf9c8a8567b70a5",
          "sha256": "c6fe3fb2324baad85dec7541bae49cecc846cf8bbbb97bd805b4883c51cab9bd",
          "sha1": "730314834f33a558890eb125cd9ab62fe699081e",
          "md5": "40da6055ca87cb7231130f0f4a68b984"
        }
      ]
    }
  ]
}
