{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.flux",
    "module": "api",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.1.0.jar",
          "url": "api-1.1.0.jar",
          "size": 7661,
          "sha512": "14fb2818eae9f868186122775a16e311c84e27aa135e965a1ab77b4ef4cffd1b7541544bf6f23a46b50b830555544c1a7da3f20f57d556ddaf7f269e93a82ca6",
          "sha256": "bdd4a079a6d465e507e3e1b9bb8df3a4547e341d9d2d039625b19d64d06c5316",
          "sha1": "825e84431326df124050531dd0117025b2d46f19",
          "md5": "536a4a1bd12e4b808a8b51a34afc1790"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.0.jar",
          "url": "api-1.1.0.jar",
          "size": 7661,
          "sha512": "14fb2818eae9f868186122775a16e311c84e27aa135e965a1ab77b4ef4cffd1b7541544bf6f23a46b50b830555544c1a7da3f20f57d556ddaf7f269e93a82ca6",
          "sha256": "bdd4a079a6d465e507e3e1b9bb8df3a4547e341d9d2d039625b19d64d06c5316",
          "sha1": "825e84431326df124050531dd0117025b2d46f19",
          "md5": "536a4a1bd12e4b808a8b51a34afc1790"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.0-sources.jar",
          "url": "api-1.1.0-sources.jar",
          "size": 10275,
          "sha512": "8e57402e9790b24e228968c5bc826b2011f915c9e13fff65c52103da37e74e7142564a6ce01466ed70e627b6e94631281cb581c8de13c9cc6b712180ed5b118d",
          "sha256": "ea9e5325b5a66a2528eae45d2045878df5b490eb0c9ef630d17b0f06bd86728f",
          "sha1": "01935340618a2e5bad89727cd5de2c83fdd7c294",
          "md5": "41c41223d8e108e6cf8e76a0bf6007c4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.0-javadoc.jar",
          "url": "api-1.1.0-javadoc.jar",
          "size": 134920,
          "sha512": "64b3015a48b3215798e863355cb552ec8bd861640c67a1c140b887d7bc297c4be8d83c2ad54963b98eaf0bcf3ce329e6a3bdbd698ee28120d52a71e5b4624acd",
          "sha256": "3060a1bdef9763c99a8803bea9baa8d4eccd07a9551041bbc0aac0f84e35a273",
          "sha1": "5b29a95b30b66afe545e831af1787eb718b99a71",
          "md5": "baccad83796cbd530d53c6784173c5b2"
        }
      ]
    }
  ]
}
