{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.axle",
    "module": "api",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.0.1.jar",
          "url": "api-1.0.1.jar",
          "size": 21362,
          "sha512": "fb81b19d7a0225651ac78a186c0ba1464b6a86acec44a33b4ba7cf15c7ea8ac120ba28889d343576bea24e21de738337efcdf36891d008e445373d9d6915ac90",
          "sha256": "29fa829b074e40c10404346d559c237ea0de31c409f22705e5b914b655ed4028",
          "sha1": "daa0911a023330bd9e935853029b0f1b4b38dcaf",
          "md5": "8f9c4d7582acc7ab6817ed27523c6436"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.1.jar",
          "url": "api-1.0.1.jar",
          "size": 21362,
          "sha512": "fb81b19d7a0225651ac78a186c0ba1464b6a86acec44a33b4ba7cf15c7ea8ac120ba28889d343576bea24e21de738337efcdf36891d008e445373d9d6915ac90",
          "sha256": "29fa829b074e40c10404346d559c237ea0de31c409f22705e5b914b655ed4028",
          "sha1": "daa0911a023330bd9e935853029b0f1b4b38dcaf",
          "md5": "8f9c4d7582acc7ab6817ed27523c6436"
        }
      ]
    }
  ]
}
