{
  "formatVersion": "1.1",
  "component": {
    "group": "org.leycm.frames",
    "module": "the-frame",
    "version": "1.3.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "the-frame-1.3.10.jar",
          "url": "the-frame-1.3.10.jar",
          "size": 44352,
          "sha512": "d13210fd070f99304c0c7aa4432037a0620a3aa8cf5f2b15f3ca7253af88c137ab68a3012c1c43900c8c171222b1874668b7246d5e8aa5b2c5fe72f89e2cd059",
          "sha256": "1f573fb4b354bfb4a8c2597a54043ff30633c82ee04bfe562e4aee6e64583933",
          "sha1": "2bcbcf2d036938d0ee2a62485f65085833d0a47f",
          "md5": "af88daf9c28ea26090bf4c322c76e31d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "the-frame-1.3.10.jar",
          "url": "the-frame-1.3.10.jar",
          "size": 44352,
          "sha512": "d13210fd070f99304c0c7aa4432037a0620a3aa8cf5f2b15f3ca7253af88c137ab68a3012c1c43900c8c171222b1874668b7246d5e8aa5b2c5fe72f89e2cd059",
          "sha256": "1f573fb4b354bfb4a8c2597a54043ff30633c82ee04bfe562e4aee6e64583933",
          "sha1": "2bcbcf2d036938d0ee2a62485f65085833d0a47f",
          "md5": "af88daf9c28ea26090bf4c322c76e31d"
        }
      ]
    }
  ]
}
