{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.neck",
    "module": "api",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.1.3.jar",
          "url": "api-1.1.3.jar",
          "size": 152591,
          "sha512": "bf546ea15e2617abd6d84a4cf53cfd379bcb3fc6c2862346706ddf8e8dd35416212388757c71bd6b02921da445d1b0f23cab713ea29860bad02141a0b98c8bc8",
          "sha256": "51059d5db6a9cdcb2591aa93bca578c99cd3a9364f4e32b7f118fe32bc3e1a71",
          "sha1": "e362850f416830912a7ac32eb64c453805d85355",
          "md5": "2efeee646cc88cb6639340db901b108d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.3.jar",
          "url": "api-1.1.3.jar",
          "size": 152591,
          "sha512": "bf546ea15e2617abd6d84a4cf53cfd379bcb3fc6c2862346706ddf8e8dd35416212388757c71bd6b02921da445d1b0f23cab713ea29860bad02141a0b98c8bc8",
          "sha256": "51059d5db6a9cdcb2591aa93bca578c99cd3a9364f4e32b7f118fe32bc3e1a71",
          "sha1": "e362850f416830912a7ac32eb64c453805d85355",
          "md5": "2efeee646cc88cb6639340db901b108d"
        }
      ]
    }
  ]
}
