{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.template",
    "module": "api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.0.2.jar",
          "url": "api-1.0.2.jar",
          "size": 8326,
          "sha512": "b481a27706467c6d0bf66043fb0a5aebd2c8ed947a99a5ff4f9ddf578a916f42867fd91aadcd0fbe6918a28c329c2f65ea20d421d5f44c38a79548893bbb7b1a",
          "sha256": "7dd6bbbe611f6aeaff5b334dffc2fae611c0a48da271a957f5e1f611e6b9cbe6",
          "sha1": "8b76439d46da8c48e8cc0a7d2b839772b8949cc8",
          "md5": "a6209a7d554de65ea4ba0218a5c6810a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.2.jar",
          "url": "api-1.0.2.jar",
          "size": 8326,
          "sha512": "b481a27706467c6d0bf66043fb0a5aebd2c8ed947a99a5ff4f9ddf578a916f42867fd91aadcd0fbe6918a28c329c2f65ea20d421d5f44c38a79548893bbb7b1a",
          "sha256": "7dd6bbbe611f6aeaff5b334dffc2fae611c0a48da271a957f5e1f611e6b9cbe6",
          "sha1": "8b76439d46da8c48e8cc0a7d2b839772b8949cc8",
          "md5": "a6209a7d554de65ea4ba0218a5c6810a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.2-sources.jar",
          "url": "api-1.0.2-sources.jar",
          "size": 7861,
          "sha512": "92b3971fa9c74a492bdbfbe30f1dd9a26804e7e953550161c8c123e1db90234d2186cdcd046389972fb963258d7aa9838d3b9ba9880a0131b7d689eed4eae304",
          "sha256": "6eaedce6cf07ec0824130407dd8e920fcc7b99b9fea4cf3e95b5041b6b88930d",
          "sha1": "383c635d1fe0c74206503709e71f1b684de35c4b",
          "md5": "22382116456229be1c810772f1e4f96d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.2-javadoc.jar",
          "url": "api-1.0.2-javadoc.jar",
          "size": 115624,
          "sha512": "a1121d3fdfc4360a130244673673e6b66fd1e1077f59c9768f74b778808c1c36fee9f11ef380db61797cf0e605108ebc416c9879f4d0f5499ff3606a142a688d",
          "sha256": "d733c64745d479ba79788da8e6f1eeb83075faa63cd70c00fed1fc2dfc4faec5",
          "sha1": "f49f86725b4f483d78425ae382f764840848a495",
          "md5": "3cf72099a93dc6baf825bf52f4a1bd14"
        }
      ]
    }
  ]
}
