{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.template",
    "module": "api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.0.2.jar",
          "url": "api-1.0.2.jar",
          "size": 8326,
          "sha512": "b481a27706467c6d0bf66043fb0a5aebd2c8ed947a99a5ff4f9ddf578a916f42867fd91aadcd0fbe6918a28c329c2f65ea20d421d5f44c38a79548893bbb7b1a",
          "sha256": "7dd6bbbe611f6aeaff5b334dffc2fae611c0a48da271a957f5e1f611e6b9cbe6",
          "sha1": "8b76439d46da8c48e8cc0a7d2b839772b8949cc8",
          "md5": "a6209a7d554de65ea4ba0218a5c6810a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.2.jar",
          "url": "api-1.0.2.jar",
          "size": 8326,
          "sha512": "b481a27706467c6d0bf66043fb0a5aebd2c8ed947a99a5ff4f9ddf578a916f42867fd91aadcd0fbe6918a28c329c2f65ea20d421d5f44c38a79548893bbb7b1a",
          "sha256": "7dd6bbbe611f6aeaff5b334dffc2fae611c0a48da271a957f5e1f611e6b9cbe6",
          "sha1": "8b76439d46da8c48e8cc0a7d2b839772b8949cc8",
          "md5": "a6209a7d554de65ea4ba0218a5c6810a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.2-sources.jar",
          "url": "api-1.0.2-sources.jar",
          "size": 7865,
          "sha512": "2b2611fbd86a864c8706ac3ff33f39660fe50747d2bb0424fb1148ff056c0023dcce9d1cf419c3ef063748a499ed2a2429676574b5af6fd7bc5346667a8983e7",
          "sha256": "37d90537a4a174c418e9b23ed6918cf7ba178c4fae3a62fedc2cc8ef8009b119",
          "sha1": "5f41dad2792d12e3973b77fc714cf6c8208e1f66",
          "md5": "05b9d59718d3a082e37c7d366764da14"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.2-javadoc.jar",
          "url": "api-1.0.2-javadoc.jar",
          "size": 115681,
          "sha512": "da1004f3dbc92e522810d9ea58add1c75b01824d29c1b63725983d552c0cc10622b8032ca98c660106f5a747345174a3a066a5804e39f945dcd7a0ba982e55b9",
          "sha256": "b1d8879037aeea9eb2bd5eeaa1b3c9750504b01ce275fed7bc1c2affcde23c14",
          "sha1": "6dff602ce41b686ac36a1a5475ed309a19feac2a",
          "md5": "4e0837b91147c5ee7b7cd5029c8b3251"
        }
      ]
    }
  ]
}
