{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.sedis",
    "module": "api",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.1.3.jar",
          "url": "api-1.1.3.jar",
          "size": 16745,
          "sha512": "40838ddf2caca4cb62ac189ebe2a4f09673506b90cc3d3012b5324be42ec48d1a4be5c69aa2c93936a857b1c76b0388266463d843fe43ff08ad42bed27d90c82",
          "sha256": "e0adbf3f768f42a311f76bd16c301dc69f599d97cd3a9af3611c1d79bb7d95c7",
          "sha1": "04483538db9d9c31ad85b7269d0f1a61a69cbbbf",
          "md5": "a17474b3fb3bb20e1af20d3304360794"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.3.jar",
          "url": "api-1.1.3.jar",
          "size": 16745,
          "sha512": "40838ddf2caca4cb62ac189ebe2a4f09673506b90cc3d3012b5324be42ec48d1a4be5c69aa2c93936a857b1c76b0388266463d843fe43ff08ad42bed27d90c82",
          "sha256": "e0adbf3f768f42a311f76bd16c301dc69f599d97cd3a9af3611c1d79bb7d95c7",
          "sha1": "04483538db9d9c31ad85b7269d0f1a61a69cbbbf",
          "md5": "a17474b3fb3bb20e1af20d3304360794"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.3-sources.jar",
          "url": "api-1.1.3-sources.jar",
          "size": 16032,
          "sha512": "e84d0d0de0f8afb82078cf8345f434c5e7aa94bb253ddccee8bb2e91cabbd071bc8f4330b2578e3f6c2214f6305c42f2510e7b7fb658e16625112c70dfd4c751",
          "sha256": "0e11e6b829834a2a321f79efb376ff71f78cdd14ca65b2a1b5dd7b19fbcc270b",
          "sha1": "f23b6baec6016d412e2112e14c50e5aef32963a2",
          "md5": "f7b9bfc3ccd92e939b7b91fe488f8083"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.3-javadoc.jar",
          "url": "api-1.1.3-javadoc.jar",
          "size": 124328,
          "sha512": "46692faa83d4c1c8c1f140e42a93e39e1a91d74ca6378380d03dcbb85b1104f31a4d7cc3dd1827ff2a9dd63324312d6c28c7d8bddcecae448d703c1b31443803",
          "sha256": "fbf41f68ca1f0e95fe90f6b257be9e761f95ed3928ae02feafa6bd2ec0bad198",
          "sha1": "d73004476d1a47b59ed68e89530e8e0359acf4e7",
          "md5": "007c280a5aedaffe7417c912f590a1a3"
        }
      ]
    }
  ]
}
