{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.linguae",
    "module": "api",
    "version": "1.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.1.4.jar",
          "url": "api-1.1.4.jar",
          "size": 8195,
          "sha512": "9f48ad02584000747d42f79345454fc2593f3561e18e6adbc138ba332490e643bcea77476146f071e26d9ade73310202beb21d3dadfd2e8d9329be1d7407c1b9",
          "sha256": "51c040d6b506edbec26f87eaa67ca27cd8dc4e22341ffa1bddd18a962445ecf8",
          "sha1": "d8e6e23d28d28062a162b2b81f55b773723e99c4",
          "md5": "d492d874abaa5130e1a2fdccaa7f740f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.4.jar",
          "url": "api-1.1.4.jar",
          "size": 8195,
          "sha512": "9f48ad02584000747d42f79345454fc2593f3561e18e6adbc138ba332490e643bcea77476146f071e26d9ade73310202beb21d3dadfd2e8d9329be1d7407c1b9",
          "sha256": "51c040d6b506edbec26f87eaa67ca27cd8dc4e22341ffa1bddd18a962445ecf8",
          "sha1": "d8e6e23d28d28062a162b2b81f55b773723e99c4",
          "md5": "d492d874abaa5130e1a2fdccaa7f740f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.4-sources.jar",
          "url": "api-1.1.4-sources.jar",
          "size": 8051,
          "sha512": "c34c09078853186aa0967f1168b9a5f2221102f5a99d6f04d6f26f4f4a42649d08b69968a374ba4829b34ab70cc13906e5529f4eeb300885833699635578e015",
          "sha256": "330ab5e625548e52e0c14e561649d45bd2da75dcb34aa96886940498f82c4e92",
          "sha1": "d7dfbe2d3f05906dae44055b33f587386e3cf560",
          "md5": "1f308e1a09bf05b1d586ceabdfdaf5fb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.4-javadoc.jar",
          "url": "api-1.1.4-javadoc.jar",
          "size": 116144,
          "sha512": "5a21c9fcb22e1ac640dbd0792069fc0e21f66b3a5871509a73e3c1ae39296f11f6c611c971a551bbb7783559dae5088d9aa8b73bde045da3381dd33aeed3cca4",
          "sha256": "70e9d029cbb5096e68354b7459ab16fc95d6f3f8aa862ca00040539e24a62dac",
          "sha1": "c81a782268953735485000316afac84c786f6f89",
          "md5": "c1d7cacc0e4b08a79492982dff2dbe31"
        }
      ]
    }
  ]
}
