{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.sedis",
    "module": "api",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.1.2.jar",
          "url": "api-1.1.2.jar",
          "size": 15573,
          "sha512": "356575dfce54730778a01b9e9abfb3b94778796bc46a1df3c89eda96b2a6d7f8111cf0036d9e1c9b02f4e1b04e5ed50b78ad03ebb3a8035341a0c4e14f76a1aa",
          "sha256": "03c486021563ac0ba0ebf7e50ea68eac27f18e5cf0a24a5c7837344fb898804b",
          "sha1": "c1e5deb32dcb21b2fcd7851f74390ff80658c4c1",
          "md5": "370d94a7fb81fe3d75b22af12a6f3b62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.2.jar",
          "url": "api-1.1.2.jar",
          "size": 15573,
          "sha512": "356575dfce54730778a01b9e9abfb3b94778796bc46a1df3c89eda96b2a6d7f8111cf0036d9e1c9b02f4e1b04e5ed50b78ad03ebb3a8035341a0c4e14f76a1aa",
          "sha256": "03c486021563ac0ba0ebf7e50ea68eac27f18e5cf0a24a5c7837344fb898804b",
          "sha1": "c1e5deb32dcb21b2fcd7851f74390ff80658c4c1",
          "md5": "370d94a7fb81fe3d75b22af12a6f3b62"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.2-sources.jar",
          "url": "api-1.1.2-sources.jar",
          "size": 13374,
          "sha512": "6709d35b83c3041d723ef4756b8773b8e1c322f8bb8743910f6616be9c3017ce74a599dac0090c4f839d617a2e5e60d0780fd99270c651ca94bc7c807ae4ebd5",
          "sha256": "1d81589aa4461c0d0f080d5cf25c75eb0888fe69e20dd1290fefeb93dfd96fdc",
          "sha1": "f59a1e49ac6bf559963501c2d87104910054d593",
          "md5": "79796ff37b9902f73c6f1125cf480463"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.2-javadoc.jar",
          "url": "api-1.1.2-javadoc.jar",
          "size": 120479,
          "sha512": "db6371d1a3adc23f659c1cb1e7744d3b7ca311e1ce0b959776b20bb7b09c6d703708bd46031db0b7f5378e55ce50f79b2f2ffce26066e3141e9c33347829fa84",
          "sha256": "4d45c7cb7f48c6aede00d2a07756ed6e527463f6d44808194f1d569d1083fc2b",
          "sha1": "f5303f7ba2df345cbf7821287d5be1c9c87b4ade",
          "md5": "c145e359b854bef67c585f60d170b8b1"
        }
      ]
    }
  ]
}
