{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.sedis",
    "module": "api",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.1.2.jar",
          "url": "api-1.1.2.jar",
          "size": 15568,
          "sha512": "29c6b4a2dbcd45d05fbb0252503ddb9c47eb9b712913165a1143bc4439747250bec3e4ea97ac91e67b804172011511b5dc28415316d5028b58505e3dc7367a74",
          "sha256": "b2fe90da943a1b61377fe9b69d5181746e45619b1805832a528216283c69354d",
          "sha1": "1f03299102e687dc9aa0a2b5affb9c7cc87a1c88",
          "md5": "83ced236ac4318f74c99debc916588a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.2.jar",
          "url": "api-1.1.2.jar",
          "size": 15568,
          "sha512": "29c6b4a2dbcd45d05fbb0252503ddb9c47eb9b712913165a1143bc4439747250bec3e4ea97ac91e67b804172011511b5dc28415316d5028b58505e3dc7367a74",
          "sha256": "b2fe90da943a1b61377fe9b69d5181746e45619b1805832a528216283c69354d",
          "sha1": "1f03299102e687dc9aa0a2b5affb9c7cc87a1c88",
          "md5": "83ced236ac4318f74c99debc916588a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.2-sources.jar",
          "url": "api-1.1.2-sources.jar",
          "size": 13376,
          "sha512": "556f802d1561cf9d12d9a1e3a69d83c7641e918734c7488be299af5d88ee5990fa9022da7cf1a322d2c4dc4ff140505fb1883a08ada93099a23a5bee213d58e5",
          "sha256": "080577d6a3f087697266a7382f621dfbefd1b20fac77f474e7c05e7ca3a8548d",
          "sha1": "4481512c1d72fbd8d165e36e2f5e0cb867a11415",
          "md5": "c1ebd72e57b466c25a950885472a552b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.2-javadoc.jar",
          "url": "api-1.1.2-javadoc.jar",
          "size": 120483,
          "sha512": "42ea9eb9937094cbacad3d2ea435dc7a7545faf7c8e0ebc44d57560e0804918d28828d26a9457b32e385aca59c88144d6e5754c40898cc4a86ae9bc210765e55",
          "sha256": "62c9f506c6cbc7ebe45e50a8084608f3543e263a6912b35d8294a72bba986924",
          "sha1": "7655cb8e2b7d41d88629c5ae2feea784afe47cef",
          "md5": "48ec7bb5ccd4d8f232ced57d61b730cd"
        }
      ]
    }
  ]
}
