{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.sedis",
    "module": "api",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.1.2.jar",
          "url": "api-1.1.2.jar",
          "size": 15578,
          "sha512": "dc0c10d2a5f95bdd43b5906e32b083398a13e18c2ce829b3e259f4710aa0995475c5a9b89d774a58b68d6ecd3c7378b599a83ae0b81f12a62259d4d0a3d7995b",
          "sha256": "98febcc9352e5ef194f6600a71353577ab5232f0b73d5c8bbe53280b0f12f41b",
          "sha1": "4e6cef70c0b62c7c9f26201d7fadecf59308bf7b",
          "md5": "2d256f250e2de415c66cbe0bb1db1ac5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.2.jar",
          "url": "api-1.1.2.jar",
          "size": 15578,
          "sha512": "dc0c10d2a5f95bdd43b5906e32b083398a13e18c2ce829b3e259f4710aa0995475c5a9b89d774a58b68d6ecd3c7378b599a83ae0b81f12a62259d4d0a3d7995b",
          "sha256": "98febcc9352e5ef194f6600a71353577ab5232f0b73d5c8bbe53280b0f12f41b",
          "sha1": "4e6cef70c0b62c7c9f26201d7fadecf59308bf7b",
          "md5": "2d256f250e2de415c66cbe0bb1db1ac5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.2-sources.jar",
          "url": "api-1.1.2-sources.jar",
          "size": 13500,
          "sha512": "1a21505991007b85c9030856a5eb61b51c7b45771b22e1fb298a798a33da334e49dbfe9917de84cc729b3d866cff3b090ae19b5b1fc7e6119c17200c043a4e19",
          "sha256": "7d3bf42acc2991497a7d838e0a97e0a15107f178602b264ff712046adfbac759",
          "sha1": "d2759319533de44afa71ee381eca4a8d700ee4d9",
          "md5": "5472139b18ac1036c7a3cdd89db4fdb0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.2-javadoc.jar",
          "url": "api-1.1.2-javadoc.jar",
          "size": 120497,
          "sha512": "ae364bf6e5f0924cc1e88e8b20d71844831507dc59bc76ebf7315cd05a1c0a87b7ae469e54cbbb350cb9cfe03b2607d4d666917e29d80c15d5afc0339f929165",
          "sha256": "7c2524820d464979728a415501dffe1e41b2f470e1f3b7542920d468ccdd0273",
          "sha1": "dcddcecbecf35e58fa91d718072b32f32c58f3b0",
          "md5": "bd877a5c78e14642dd85dfd729d202b1"
        }
      ]
    }
  ]
}
