{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.neck",
    "module": "api",
    "version": "1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.1.6.jar",
          "url": "api-1.1.6.jar",
          "size": 14430,
          "sha512": "e4c5728dfa495bcaf1941f4a3dfb90cd7f63f401489fd2421c2c653f8d83af8e531c407e30d895c96c6f1b8721d8a9a71077b5004c18382ce21ee898ca7fcdb8",
          "sha256": "108790044e087ee7349037b63523f46ccfa826336e23c99b7759c2489b23383e",
          "sha1": "e838e46695c05b5ade41860e7372377f51787eba",
          "md5": "e87890b0452aea7ec270a1c231429153"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.6.jar",
          "url": "api-1.1.6.jar",
          "size": 14430,
          "sha512": "e4c5728dfa495bcaf1941f4a3dfb90cd7f63f401489fd2421c2c653f8d83af8e531c407e30d895c96c6f1b8721d8a9a71077b5004c18382ce21ee898ca7fcdb8",
          "sha256": "108790044e087ee7349037b63523f46ccfa826336e23c99b7759c2489b23383e",
          "sha1": "e838e46695c05b5ade41860e7372377f51787eba",
          "md5": "e87890b0452aea7ec270a1c231429153"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.6-sources.jar",
          "url": "api-1.1.6-sources.jar",
          "size": 15050,
          "sha512": "67a789cccf3f5a52b588d612dc43095267ec137cf38497a58949010cbc1c1d89d103ea996f294a1c47a557b89c7c6771c36ef8cd7ac357a8e66193e4ed17abd6",
          "sha256": "ea89d931affb69099d8796a1b918047d3d94ff807fbdae5371d5bca6ee58aabd",
          "sha1": "01ba98aa682c6bd6884427c6f80c768b14b5bfae",
          "md5": "adcad9fbf6d87d6bcfdad0a40d69eb47"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.6-javadoc.jar",
          "url": "api-1.1.6-javadoc.jar",
          "size": 142711,
          "sha512": "69423737b3b91ada107e57440518eb0b42e596dbbd8c13a442a43ba518e704c8c532c0c22db7835f2334f6141f42154e24693b7a2324abc5f3f916e26473da23",
          "sha256": "2fd05626453cf4f8c901fa059cbf42879900f5dd85fd94c2579876018803fd9d",
          "sha1": "fe60fdf68be4ccd1286cd904dc72a60c38032a84",
          "md5": "7d8e7d5f50e71508b2bd93a5fb4d0cd8"
        }
      ]
    }
  ]
}
