{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.neck",
    "module": "api",
    "version": "1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.1.6.jar",
          "url": "api-1.1.6.jar",
          "size": 14430,
          "sha512": "4d90023b8baffc4dbc6f0e25e7f8a72527f5dadccf045df7c9371d73f2530d46ae19f71b281f1c38f945d60169bf0766ac2cce8eccf23b5f16408b58e7426579",
          "sha256": "fe1dc53048bb547cb496f4c6297f2ecd87ed05551d0921238007e082b1fe3300",
          "sha1": "261d84726bc580c2be82a3302887a52699a3a9d4",
          "md5": "701311f76c4b9ce48e29c2ee456cae27"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.6.jar",
          "url": "api-1.1.6.jar",
          "size": 14430,
          "sha512": "4d90023b8baffc4dbc6f0e25e7f8a72527f5dadccf045df7c9371d73f2530d46ae19f71b281f1c38f945d60169bf0766ac2cce8eccf23b5f16408b58e7426579",
          "sha256": "fe1dc53048bb547cb496f4c6297f2ecd87ed05551d0921238007e082b1fe3300",
          "sha1": "261d84726bc580c2be82a3302887a52699a3a9d4",
          "md5": "701311f76c4b9ce48e29c2ee456cae27"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.6-sources.jar",
          "url": "api-1.1.6-sources.jar",
          "size": 15050,
          "sha512": "f8923f43ce5e291655bf184365d70298a83bb2b52e798ddf8eb8df93e3584638799b868e1c2255a00fc75f246ca47d19f4e4beca85b89112e4cc634b1d6dcfa6",
          "sha256": "b688a926c76706747830d843345fb309d0cf7ca23061b1bba7c004168414905a",
          "sha1": "92bde0b8976ed4cf8390df1eb4691f66e5d4642c",
          "md5": "f4d15521e51fb70aa9f299bdeaa96697"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.6-javadoc.jar",
          "url": "api-1.1.6-javadoc.jar",
          "size": 142842,
          "sha512": "6bab02f0963fd2d4a2adbd7c40763047d68c9276df68644b996201c0c3ab4f6f96b0e0a5e60f897b35783185b0aad21f9941dcb52f35e85d13512f82856f4c56",
          "sha256": "b48fb3eaeced568114d10ed03750eb16e975f95b958bf4d989e5da7fc296c773",
          "sha1": "c02b1fc653f762e95b92371474e55f306ec0c971",
          "md5": "4be48c6fb376e31cfce7d21869694d8f"
        }
      ]
    }
  ]
}
