{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.vault",
    "module": "api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.0.3.jar",
          "url": "api-1.0.3.jar",
          "size": 8064,
          "sha512": "e6f4115cf285c72ba1d21a997fc0e06ea3fbeec953b641d90e12f31e20ed6b6977d44a9007e2490ee6fd5c1ca178cf8c5cc65eb06637cf8c85eec718e04f395d",
          "sha256": "d70011ed1a5f953623b06d9f51fb3bddd322dceb17350537736d329fcf02038a",
          "sha1": "ee189a3e4140e3dbf3e41d732cca0802ae80c5dc",
          "md5": "b0cd5def5c6599af23c50de06fa2fc22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.3.jar",
          "url": "api-1.0.3.jar",
          "size": 8064,
          "sha512": "e6f4115cf285c72ba1d21a997fc0e06ea3fbeec953b641d90e12f31e20ed6b6977d44a9007e2490ee6fd5c1ca178cf8c5cc65eb06637cf8c85eec718e04f395d",
          "sha256": "d70011ed1a5f953623b06d9f51fb3bddd322dceb17350537736d329fcf02038a",
          "sha1": "ee189a3e4140e3dbf3e41d732cca0802ae80c5dc",
          "md5": "b0cd5def5c6599af23c50de06fa2fc22"
        }
      ]
    }
  ]
}
