{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.template",
    "module": "api",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.0.1.jar",
          "url": "api-1.0.1.jar",
          "size": 1045,
          "sha512": "107e56a7509b6f806bb34e6556ee421c310b8b5f1dd1aeaeabd9f21246b742151edffb0feb647c1c646e93c8950377c26bcf5206e5471d2f2de0edcd27fe69b8",
          "sha256": "7fff0c244ab43976e064415f3ac4df3fddc0c933c2a0b4803f533bfcf8240d0e",
          "sha1": "55b2c5027efdcf8baf22bde29d789c626515703f",
          "md5": "b0ed5dc0976cda2b13356b479bf8e9ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.1.jar",
          "url": "api-1.0.1.jar",
          "size": 1045,
          "sha512": "107e56a7509b6f806bb34e6556ee421c310b8b5f1dd1aeaeabd9f21246b742151edffb0feb647c1c646e93c8950377c26bcf5206e5471d2f2de0edcd27fe69b8",
          "sha256": "7fff0c244ab43976e064415f3ac4df3fddc0c933c2a0b4803f533bfcf8240d0e",
          "sha1": "55b2c5027efdcf8baf22bde29d789c626515703f",
          "md5": "b0ed5dc0976cda2b13356b479bf8e9ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.1-sources.jar",
          "url": "api-1.0.1-sources.jar",
          "size": 1400,
          "sha512": "88db737e332775a273d3e463c61c44ab790c3ea14b4719e5850150f3f33f996c430c0bdb94c88bbe45dfe31152d03329fd28052f68a22e735d95d3aa4524669e",
          "sha256": "a608d149725423989137ccb1ba528c831fdecd27408be56193fefa1a916a681b",
          "sha1": "4db8a28c1dc13b3eed9543c44f7e208cc829c317",
          "md5": "5c9701db528f566d9e14a867b1e9043d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.1-javadoc.jar",
          "url": "api-1.0.1-javadoc.jar",
          "size": 90934,
          "sha512": "cacd188506f144fe8f310767f27731677dd7030a1428681d5f52a1874c2601b8e451687f5890521903d836f6f913e7a8cbc1031e97a35b98dd776168b6818e00",
          "sha256": "f0f6cde827dbfd7002dca09b41f1d218ddbf189bac9a93a4ddaf07398b328ca5",
          "sha1": "bee137b59416151e77434f56a7c4285c7773a69f",
          "md5": "980c43dbdc303c191e86173b40d2ffe6"
        }
      ]
    }
  ]
}
