{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.sedis",
    "module": "api",
    "version": "1.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.1.5.jar",
          "url": "api-1.1.5.jar",
          "size": 17038,
          "sha512": "91d178b931c319a5fb9e1259b3c179d7840e47196251aae42ebb2b3d6f52e7991455b6e214ebf6a3883d62cbbf79a437af4f94056644e07647a076469b97be2e",
          "sha256": "7efa82113853d903b9302023b88a02228bace94a40b628cf7717422711ab4081",
          "sha1": "cd67950be142e6724f0ffcfd6bbbcd9103aa7ba7",
          "md5": "032d785da36627f1fd417e1f83141b12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.5.jar",
          "url": "api-1.1.5.jar",
          "size": 17038,
          "sha512": "91d178b931c319a5fb9e1259b3c179d7840e47196251aae42ebb2b3d6f52e7991455b6e214ebf6a3883d62cbbf79a437af4f94056644e07647a076469b97be2e",
          "sha256": "7efa82113853d903b9302023b88a02228bace94a40b628cf7717422711ab4081",
          "sha1": "cd67950be142e6724f0ffcfd6bbbcd9103aa7ba7",
          "md5": "032d785da36627f1fd417e1f83141b12"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.5-sources.jar",
          "url": "api-1.1.5-sources.jar",
          "size": 16130,
          "sha512": "bfb25c8dd49a45f364297d6ae749c79e68e19dd32eb36f094bc285a4edf739535cd724c00a9fb59af03ba76797f185457252416e434baa6f9c0714970605955a",
          "sha256": "f30edd996e97fdeb0c9af785c6d2384aad738b82c7da26e51fa85f0534c60799",
          "sha1": "ba74dc17cac936cd3b3c36bbae8aad191f9c4174",
          "md5": "2a427bd3506caf9d8aef5fa87bc9039c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.5-javadoc.jar",
          "url": "api-1.1.5-javadoc.jar",
          "size": 124734,
          "sha512": "223292d19024e9172874e8477e46298be6305fc76727112f0f9a5e25d61d214ea809edf681eb5c22f43a5d1ae4af9ba6096d86cdcb604a7364ef1569d6f7bb8d",
          "sha256": "f4cf2f009fa5b5a00ffe6f7850af7929e08ccf5f31323a1bede362130637cd74",
          "sha1": "6ce6fb1f8bb07d11a70e7ee0c8caf3d64ea80704",
          "md5": "1199d6edc6bd1f40c4ee2dc7d51947ca"
        }
      ]
    }
  ]
}
