{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.template",
    "module": "api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.0.3.jar",
          "url": "api-1.0.3.jar",
          "size": 8126,
          "sha512": "9f6cd6f18ed5a0e3924d7503fa38e6e4e8fc3071f3adc29792a795479693b4fa93cc3bf4d7575692303c054a47c609ac6a0b9d8e2131f2373dc145c6b0419d5e",
          "sha256": "554aa99ee081daf4bcc322b918ec73e24c706811d8021734c0d957958331c4e0",
          "sha1": "5d7606bda09b55b75f1567198cbff3360929369d",
          "md5": "8a894b825f4b44401a4475a3e6f9d2ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.3.jar",
          "url": "api-1.0.3.jar",
          "size": 8126,
          "sha512": "9f6cd6f18ed5a0e3924d7503fa38e6e4e8fc3071f3adc29792a795479693b4fa93cc3bf4d7575692303c054a47c609ac6a0b9d8e2131f2373dc145c6b0419d5e",
          "sha256": "554aa99ee081daf4bcc322b918ec73e24c706811d8021734c0d957958331c4e0",
          "sha1": "5d7606bda09b55b75f1567198cbff3360929369d",
          "md5": "8a894b825f4b44401a4475a3e6f9d2ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.3-sources.jar",
          "url": "api-1.0.3-sources.jar",
          "size": 8017,
          "sha512": "7b751343bfc6ab3faecb58147e6932df02b5dd419431f6a755b6d01adcea763582a0a7ee19f86aa1631df3d306c70c1a819a91538645218e91ea4f4b099258eb",
          "sha256": "3481f5cb2e4ba34917932bd87a26fcd50de2d81c57d36f7df5da712b391d2de8",
          "sha1": "cdb8f096ccc3d3267e0da9f960393bb1c73105cc",
          "md5": "e5fb9dbd98ce215fd67a24420cb3916b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.3-javadoc.jar",
          "url": "api-1.0.3-javadoc.jar",
          "size": 116555,
          "sha512": "a91c6ba5ba6af58c927e3ff02d5645154b2520ef9bd0605ae4ca4cdf22f50a009d4e1775e8e99ea589b3245c1e3c85044eb382183d55ead9692f4cee6f61dcd1",
          "sha256": "7adc35b1d44d3be68d44d6994faabde8fb7988dcd5a044b51131d4fb25a96456",
          "sha1": "11e4feae7c74bf4abcc9a9bc0acd54beb54c874b",
          "md5": "58761aef0f61ccf0c938e48966e90da1"
        }
      ]
    }
  ]
}
