{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.template",
    "module": "api",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.0.3.jar",
          "url": "api-1.0.3.jar",
          "size": 8127,
          "sha512": "0de982f783aa1175a577abe11b8666bd89dc2575abd5295b4cb1c74ae2621d6c5ce1660d41ffc404ff0549f96e37e67a6802fb94cdf758fe2d655015697c9f2b",
          "sha256": "59dbef2c1978b79c011da3983d7e389923e37a1964ef61000194118ad6824198",
          "sha1": "619b2cb4e3912de59d7898ee325dac82f13f9f8d",
          "md5": "a2ed968e83b50afeaeb5caa1c42b23e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.3.jar",
          "url": "api-1.0.3.jar",
          "size": 8127,
          "sha512": "0de982f783aa1175a577abe11b8666bd89dc2575abd5295b4cb1c74ae2621d6c5ce1660d41ffc404ff0549f96e37e67a6802fb94cdf758fe2d655015697c9f2b",
          "sha256": "59dbef2c1978b79c011da3983d7e389923e37a1964ef61000194118ad6824198",
          "sha1": "619b2cb4e3912de59d7898ee325dac82f13f9f8d",
          "md5": "a2ed968e83b50afeaeb5caa1c42b23e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.3-sources.jar",
          "url": "api-1.0.3-sources.jar",
          "size": 7995,
          "sha512": "2bd4d80629ba9c36f1b496c964061aa510dd0cbd308d58ca86d3622af9fea41b74d5fc9523c40caa33dad98b4fa2d34843571102b3180ca822c35451ab3a0dbf",
          "sha256": "a54edb28819a714398490127f572c7a81c0fac283f699aeaa55d4c97e98bb2f7",
          "sha1": "1a9243213736f3f8f6c25e32e7f6de89ae523bdf",
          "md5": "a2e85a8ad49c1533e459088a8fe3b31c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.0.3-javadoc.jar",
          "url": "api-1.0.3-javadoc.jar",
          "size": 116491,
          "sha512": "044c20654f39cdb734fe3895cd675ada80fe4eacf9339fde2487b4c4fee15be9f4e0d2acd40e7c69d28c2d0021c4a3c1d900e9b8b38c88e3e250e1db6b676009",
          "sha256": "52f2cb97a7299a9ba4a30a97ff8ba810dd0b648ecc0ed4f0f253e8338fa263fe",
          "sha1": "76099a1ce391d45c9e2f2df20c62b2b73f5cfe21",
          "md5": "66cdb9171eca7f528d6899616d681115"
        }
      ]
    }
  ]
}
