{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.linguae",
    "module": "common",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.2.0.jar",
          "url": "common-1.2.0.jar",
          "size": 38917,
          "sha512": "6afee7f27ab6fb72867b4fa27948981dab467cd634d0ef5f861dfdf129a1e70bdbd29f5da90ccde9bcf3cd26c57b6dfd8449bd7f36c070552b25a1b2b16ec5cb",
          "sha256": "59d95761b29d2bd2b95f78e6b278280df463f80f7c77084c67f62de6509e5efe",
          "sha1": "d5b24359a9ae90208816172f7d468531b6c123f4",
          "md5": "cd1cb5ea341c323e2ec33b115fa71bad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.leycm.neck",
          "module": "api",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "de.leycm.linguae",
          "module": "api",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.2.0.jar",
          "url": "common-1.2.0.jar",
          "size": 38917,
          "sha512": "6afee7f27ab6fb72867b4fa27948981dab467cd634d0ef5f861dfdf129a1e70bdbd29f5da90ccde9bcf3cd26c57b6dfd8449bd7f36c070552b25a1b2b16ec5cb",
          "sha256": "59d95761b29d2bd2b95f78e6b278280df463f80f7c77084c67f62de6509e5efe",
          "sha1": "d5b24359a9ae90208816172f7d468531b6c123f4",
          "md5": "cd1cb5ea341c323e2ec33b115fa71bad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.2.0-sources.jar",
          "url": "common-1.2.0-sources.jar",
          "size": 31234,
          "sha512": "6d0df83dd60c1727d7250712743fd1dead34215bc15ec9e6a6e1a4718740f82654131516d26296612c12ea2b8caf9ec4615bbb3f294629e95e3d23885c41c7b1",
          "sha256": "c68ea3ef4c37a0a4b303e9916fbc755e95cd6605ec925109eef79b20dac4015f",
          "sha1": "08d267622d8f32d03a1df9d202f8a91b8c1d3fb4",
          "md5": "f6f5d8474f6ba9df55352c1ee18548da"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.2.0-javadoc.jar",
          "url": "common-1.2.0-javadoc.jar",
          "size": 148134,
          "sha512": "5ffaeb1b90700caad807be44b5fd67d2f85448e999c1e74ce2e7a78e32ad9599662ca2c4e795e726b5a614a707c8785d5d09fa25962980c8e9a5c2ecba8338d2",
          "sha256": "b4e7acea6131b0d1694cc51ef39e84a4794d8736347a2e99c74661756831c8ef",
          "sha1": "48d2fa8752ebf2968579911ce58e5363ac3a0cf7",
          "md5": "ff7c5edc05b770b7ae3da5aed042da73"
        }
      ]
    }
  ]
}
