{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.sedis",
    "module": "api",
    "version": "1.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-1.1.6.jar",
          "url": "api-1.1.6.jar",
          "size": 17570,
          "sha512": "c52dd256d76d63c724e92fbc90ec8f7dc9680b07bb3b8e2fed00ec1201e82bf2fab3ad3ef7495a2e212551396f48d0c305c86f0cb4e5b581488aec013a40b86c",
          "sha256": "96ca4cc57fbf3dd4f2cf24632ea5b5f1ccd568e92dc30dde3a64f570d374c7b3",
          "sha1": "ee5dd606f9979069fedafebf52d702ab1e352d37",
          "md5": "190c7971a8455867e3f5c640250f97ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.6.jar",
          "url": "api-1.1.6.jar",
          "size": 17570,
          "sha512": "c52dd256d76d63c724e92fbc90ec8f7dc9680b07bb3b8e2fed00ec1201e82bf2fab3ad3ef7495a2e212551396f48d0c305c86f0cb4e5b581488aec013a40b86c",
          "sha256": "96ca4cc57fbf3dd4f2cf24632ea5b5f1ccd568e92dc30dde3a64f570d374c7b3",
          "sha1": "ee5dd606f9979069fedafebf52d702ab1e352d37",
          "md5": "190c7971a8455867e3f5c640250f97ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.6-sources.jar",
          "url": "api-1.1.6-sources.jar",
          "size": 16057,
          "sha512": "f613b5894222f33db88617c4f5f77da7f6bb9037e7d330b2941686951c6e27a318ef96119390c0d993639d8f3ef9d0af30809e61484199f6a6d948054b54f6be",
          "sha256": "5aa37ac6883205e38d0d790523e6fb597c1f98ef90bbddbab31c03e8feecb87e",
          "sha1": "42bfa6ca1307564b57aad930e57c4c4a86dbd21f",
          "md5": "68de37ceb13ffed4d6dc5bbfee4e4a99"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-1.1.6-javadoc.jar",
          "url": "api-1.1.6-javadoc.jar",
          "size": 124291,
          "sha512": "44b7aa95cdd07d41ad1f0542f90fd182e7dbc19d05752feaa97d84e467b9f32490ee048dfd1687b2840649cbe01d966df5d30f114bb189c40c45db92ba926c6c",
          "sha256": "bfd04eb302ffc1da39ba0e4ef2f3335ec55338cd58450d0393e729f420c1862b",
          "sha1": "5296550390ffb8f7be82a72dbc06f7dbb515b023",
          "md5": "d90cf7a8aac4c31103b4c186860a3a6e"
        }
      ]
    }
  ]
}
