{
  "formatVersion": "1.1",
  "component": {
    "group": "de.leycm.template",
    "module": "common",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-1.0.3.jar",
          "url": "common-1.0.3.jar",
          "size": 1090001,
          "sha512": "e2b60f92d913e1bb14ce591ca8e4cb0b3ec49ecb3757248e12d355a8307e099830bd84f54f32811556ae3f9662ff196b5305ff53d44ff6b7ccc2c262d26b44d2",
          "sha256": "90ad0982d60d6e91b2cfa00ed5ad9cc88db3b2ab2415eab9f73097628c120ea1",
          "sha1": "dd235669b8f881e153802ccca79ff2706dd7619a",
          "md5": "1d8f376b3400978ad21c03a26fcb6de7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.leycm.neck",
          "module": "api",
          "version": {
            "requires": "1.1.6"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-api",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson",
          "version": {
            "requires": "4.24.0"
          }
        },
        {
          "group": "de.leycm.template",
          "module": "api",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.3.jar",
          "url": "common-1.0.3.jar",
          "size": 1090001,
          "sha512": "e2b60f92d913e1bb14ce591ca8e4cb0b3ec49ecb3757248e12d355a8307e099830bd84f54f32811556ae3f9662ff196b5305ff53d44ff6b7ccc2c262d26b44d2",
          "sha256": "90ad0982d60d6e91b2cfa00ed5ad9cc88db3b2ab2415eab9f73097628c120ea1",
          "sha1": "dd235669b8f881e153802ccca79ff2706dd7619a",
          "md5": "1d8f376b3400978ad21c03a26fcb6de7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.0.3-sources.jar",
          "url": "common-1.0.3-sources.jar",
          "size": 1077017,
          "sha512": "0cd438788991322a13972320cf6c3415046cebaec98a025f9a93584220ae0c6e560ed748099d4c71cb7c818bbc1d7df939db4eb9e37b319ba10a52cb96a635b6",
          "sha256": "719932eedd015b1035995a49437e89f179b18bb28a5a1aede277510bb06bffcd",
          "sha1": "001325cb375600907ac82eb58270abbecbad43c7",
          "md5": "dc74a3728c1b988c9f79b468d4a90c94"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.0.3-javadoc.jar",
          "url": "common-1.0.3-javadoc.jar",
          "size": 1201636,
          "sha512": "7acbd39cfb7c21e690123e90b6cbb28fd745bef65dd8de8185780af1f67edd1e3d59188186fd1c04526924a004551944c0ccc8b5d82dfb9cbdf17720febd2e8d",
          "sha256": "4f1c3a74d03c684811dd61fa73d66bbba0b35fc28acf1517f991f3768dbe6230",
          "sha1": "6ed08eff3c205c521a625d9db376c8f68eb3709b",
          "md5": "5b6fc43377014bb9a4420e9e899d04c3"
        }
      ]
    }
  ]
}
