{
  "formatVersion": "1.1",
  "component": {
    "group": "org.leycm.frames",
    "module": "the-frame",
    "version": "1.3.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "the-frame-1.3.15.jar",
          "url": "the-frame-1.3.15.jar",
          "size": 46735,
          "sha512": "ee7fce804c28240c5756147675f2174b6577e6751cf5dffa33ab3a0d207f6f2938f0adc0cc43c401dd8a7601dcfbe8522662a520f25d3a7ea36e60f0a9fc2973",
          "sha256": "65df69e81df2868042e7d607b6d13a518c39849c3a23940b6fc0ff8b854579ac",
          "sha1": "bfb3b45a1bfe448eef174c86d6a2bd761b106ac1",
          "md5": "47434d044e2aaaedd47e0b0afe616ebd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "the-frame-1.3.15.jar",
          "url": "the-frame-1.3.15.jar",
          "size": 46735,
          "sha512": "ee7fce804c28240c5756147675f2174b6577e6751cf5dffa33ab3a0d207f6f2938f0adc0cc43c401dd8a7601dcfbe8522662a520f25d3a7ea36e60f0a9fc2973",
          "sha256": "65df69e81df2868042e7d607b6d13a518c39849c3a23940b6fc0ff8b854579ac",
          "sha1": "bfb3b45a1bfe448eef174c86d6a2bd761b106ac1",
          "md5": "47434d044e2aaaedd47e0b0afe616ebd"
        }
      ]
    }
  ]
}
